package checkpoint

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"
)

// newSessionDir creates a session directory standing in for a real one. Every
// test here touches the filesystem: the behaviour under test is "what is on disk
// after a turn", which an in-memory fake would not exercise at all.
func newSessionDir(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	// The real layout nests the checkpoint directory inside the session's.
	if err := os.MkdirAll(filepath.Join(dir, "checkpoints"), 0o700); err != nil {
		t.Fatalf("seeding session dir: %v", err)
	}
	return dir
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
}

func read(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	return string(data)
}

func TestCaptureRecordsTheContentsBeforeTheWrite(t *testing.T) {
	dir := newSessionDir(t)
	target := filepath.Join(dir, "main.go")
	write(t, target, "original")

	m := New()
	if _, err := m.Begin(dir, 7, "add a function"); err != nil {
		t.Fatalf("Begin: %v", err)
	}
	if err := m.Capture(dir, target); err != nil {
		t.Fatalf("Capture: %v", err)
	}

	// The turn now overwrites the file.
	write(t, target, "rewritten by the agent")

	cps, err := m.List(dir)
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	if len(cps) != 1 {
		t.Fatalf("got %d checkpoints, want 1", len(cps))
	}
	if len(cps[0].Files) != 1 {
		t.Fatalf("got %d snapshots, want 1", len(cps[0].Files))
	}
	if got := string(cps[0].Files[0].Content); got != "original" {
		t.Errorf("snapshot content = %q, want %q — this is the regression the before-callback exists for", got, "original")
	}
	if cps[0].EventIndex != 7 {
		t.Errorf("EventIndex = %d, want 7", cps[0].EventIndex)
	}
}

func TestRestoreUndoesTheWrite(t *testing.T) {
	dir := newSessionDir(t)
	target := filepath.Join(dir, "main.go")
	write(t, target, "original")

	m := New()
	_, _ = m.Begin(dir, 0, "edit")
	_ = m.Capture(dir, target)
	write(t, target, "rewritten by the agent")

	cps, _ := m.List(dir)
	out := Restore(&cps[0])

	if out.Restored != 1 || out.Failed != 0 {
		t.Errorf("Outcome = %+v, want 1 restored and no failures", out)
	}
	if got := read(t, target); got != "original" {
		t.Errorf("file = %q, want %q", got, "original")
	}
}

func TestRestoreRemovesFilesTheTurnCreated(t *testing.T) {
	dir := newSessionDir(t)
	target := filepath.Join(dir, "generated.go")

	m := New()
	_, _ = m.Begin(dir, 0, "generate")
	_ = m.Capture(dir, target) // the file does not exist yet
	write(t, target, "// Code generated by the agent")

	cps, _ := m.List(dir)
	out := Restore(&cps[0])

	if out.Deleted != 1 {
		t.Errorf("Deleted = %d, want 1 — a file the turn created must not survive a rewind", out.Deleted)
	}
	if _, err := os.Stat(target); !os.IsNotExist(err) {
		t.Errorf("the file still exists after the restore (stat err = %v)", err)
	}
}

func TestRestoreIsAPrefixNotTheLastEdit(t *testing.T) {
	// The turn writes the same file three times. Only the state from before the
	// turn can be right; restoring the state before the last write would leave
	// two of the three edits in place, which is the bug a re-capture-per-write
	// implementation has.
	dir := newSessionDir(t)
	target := filepath.Join(dir, "f.txt")
	write(t, target, "v0")

	m := New()
	_, _ = m.Begin(dir, 0, "three edits")
	for i, v := range []string{"v1", "v2", "v3"} {
		if err := m.Capture(dir, target); err != nil {
			t.Fatalf("Capture %d: %v", i, err)
		}
		write(t, target, v)
	}

	cps, _ := m.List(dir)
	if got := len(cps[0].Files); got != 1 {
		t.Errorf("captured %d snapshots for one file, want 1", got)
	}
	Restore(&cps[0])
	if got := read(t, target); got != "v0" {
		t.Errorf("file = %q, want %q — the pre-turn contents", got, "v0")
	}
}

func TestSymlinksAreSkippedAndCounted(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("symlink creation needs elevation on Windows")
	}
	dir := newSessionDir(t)
	real := filepath.Join(dir, "real.txt")
	write(t, real, "real contents")
	link := filepath.Join(dir, "link.txt")
	if err := os.Symlink(real, link); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}

	m := New()
	_, _ = m.Begin(dir, 0, "edit through a link")
	_ = m.Capture(dir, link)

	cps, _ := m.List(dir)
	if got := cps[0].SkippedSymlinks; got != 1 {
		t.Errorf("SkippedSymlinks = %d, want 1", got)
	}

	out := Restore(&cps[0])
	if out.SkippedSymlinks != 1 {
		t.Errorf("Outcome.SkippedSymlinks = %d, want 1", out.SkippedSymlinks)
	}
	// The point of skipping: the target must be untouched, because following
	// the link would have rewritten a file the agent never named.
	if got := read(t, real); got != "real contents" {
		t.Errorf("the symlink target was modified: %q", got)
	}
	if !strings.Contains(out.String(), "symlink") {
		t.Errorf("Outcome.String() = %q, want it to name the skipped symlinks", out.String())
	}
}

func TestOversizedFilesAreSkippedNotTruncated(t *testing.T) {
	dir := newSessionDir(t)
	target := filepath.Join(dir, "big.bin")
	big := make([]byte, maxSnapshotBytes+1)
	for i := range big {
		big[i] = 'x'
	}
	write(t, target, string(big))

	m := New()
	_, _ = m.Begin(dir, 0, "rewrite a big file")
	_ = m.Capture(dir, target)
	write(t, target, "small")

	cps, _ := m.List(dir)
	out := Restore(&cps[0])

	if out.SkippedTooLarge != 1 || out.Restored != 0 {
		t.Errorf("Outcome = %+v, want 1 skipped and nothing restored", out)
	}
	// Restoring an empty snapshot would silently destroy the user's file.
	if got := read(t, target); got != "small" {
		t.Errorf("file = %q, want it left as the turn left it", got)
	}
}

func TestCaptureOutsideATurnIsIgnored(t *testing.T) {
	// A write with no open checkpoint has no boundary to rewind to. Recording
	// it would produce a checkpoint whose index means nothing.
	dir := newSessionDir(t)
	target := filepath.Join(dir, "f.txt")
	write(t, target, "v")

	m := New()
	if err := m.Capture(dir, target); err != nil {
		t.Fatalf("Capture outside a turn = %v, want nil", err)
	}
	cps, err := m.List(dir)
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	if len(cps) != 0 {
		t.Errorf("got %d checkpoints, want 0", len(cps))
	}
}

func TestEndStopsFurtherCaptures(t *testing.T) {
	dir := newSessionDir(t)
	first := filepath.Join(dir, "first.txt")
	second := filepath.Join(dir, "second.txt")
	write(t, first, "1")
	write(t, second, "2")

	m := New()
	_, _ = m.Begin(dir, 0, "turn one")
	_ = m.Capture(dir, first)
	m.End(dir)
	_ = m.Capture(dir, second)

	cps, _ := m.List(dir)
	if got := len(cps[0].Files); got != 1 {
		t.Errorf("got %d snapshots, want 1 — the next turn's write must not join this one", got)
	}
	if m.Open(dir) {
		t.Error("Open() = true after End, want false")
	}
}

func TestBeginSupersedesAnUnfinishedCheckpoint(t *testing.T) {
	// A turn cancelled before it finishes still leaves its checkpoint open. The
	// next prompt must close it, or the two accumulate into one file and the
	// earlier index no longer describes a boundary.
	dir := newSessionDir(t)
	target := filepath.Join(dir, "f.txt")
	write(t, target, "v")

	m := New()
	_, _ = m.Begin(dir, 3, "cancelled turn")
	_ = m.Capture(dir, target)
	_, _ = m.Begin(dir, 9, "next turn")
	_ = m.Capture(dir, target)

	cps, _ := m.List(dir)
	if len(cps) != 2 {
		t.Fatalf("got %d checkpoints, want 2", len(cps))
	}
	for _, cp := range cps {
		if got := len(cp.Files); got != 1 {
			t.Errorf("checkpoint %s has %d snapshots, want 1", cp.ID, got)
		}
	}
	// The older one is listed first only after sorting; check by index instead.
	byIndex := map[int]int{}
	for _, cp := range cps {
		byIndex[cp.EventIndex] = len(cp.Files)
	}
	if byIndex[3] != 1 || byIndex[9] != 1 {
		t.Errorf("snapshots by index = %v, want one each at 3 and 9", byIndex)
	}
}

func TestListIsNewestFirst(t *testing.T) {
	dir := newSessionDir(t)
	m := New()
	base := time.Date(2026, 3, 1, 12, 0, 0, 0, time.UTC)
	for i := range 5 {
		m.now = func() time.Time { return base.Add(time.Duration(i) * time.Minute) }
		if _, err := m.Begin(dir, i, "turn"); err != nil {
			t.Fatalf("Begin %d: %v", i, err)
		}
	}

	cps, err := m.List(dir)
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	if len(cps) != 5 {
		t.Fatalf("got %d checkpoints, want 5", len(cps))
	}
	for i := 1; i < len(cps); i++ {
		if cps[i-1].CreatedAt.Before(cps[i].CreatedAt) {
			t.Errorf("checkpoint %d (%s) is newer than the one before it (%s); order must be newest first",
				i, cps[i].CreatedAt, cps[i-1].CreatedAt)
		}
	}
}

func TestKeepCapDropsTheOldest(t *testing.T) {
	dir := newSessionDir(t)
	m := New(WithKeep(3))
	base := time.Date(2026, 3, 1, 12, 0, 0, 0, time.UTC)
	for i := range 6 {
		m.now = func() time.Time { return base.Add(time.Duration(i) * time.Minute) }
		if _, err := m.Begin(dir, i, "turn"); err != nil {
			t.Fatalf("Begin %d: %v", i, err)
		}
	}

	cps, _ := m.List(dir)
	if len(cps) != 3 {
		t.Fatalf("got %d checkpoints, want 3", len(cps))
	}
	if cps[0].EventIndex != 5 {
		t.Errorf("newest checkpoint is index %d, want 5", cps[0].EventIndex)
	}
	if cps[len(cps)-1].EventIndex != 3 {
		t.Errorf("oldest kept checkpoint is index %d, want 3", cps[len(cps)-1].EventIndex)
	}
}

func TestCleanupPeriodSweepsOldCheckpoints(t *testing.T) {
	dir := newSessionDir(t)
	now := time.Date(2026, 3, 10, 12, 0, 0, 0, time.UTC)
	m := New(WithCleanupPeriod(48*time.Hour))

	m.now = func() time.Time { return now.Add(-72 * time.Hour) }
	_, _ = m.Begin(dir, 1, "ancient")
	m.now = func() time.Time { return now.Add(-24 * time.Hour) }
	_, _ = m.Begin(dir, 2, "recent")
	m.now = func() time.Time { return now }
	// The next Begin is what runs the sweep — retention is not on a timer.
	_, _ = m.Begin(dir, 3, "now")

	cps, _ := m.List(dir)
	if len(cps) != 2 {
		t.Fatalf("got %d checkpoints, want 2 — the one older than the period must be gone", len(cps))
	}
	for _, cp := range cps {
		if cp.Label == "ancient" {
			t.Error("the checkpoint older than the cleanup period survived")
		}
	}
}

func TestLabelIsBoundedAndSingleLine(t *testing.T) {
	dir := newSessionDir(t)
	m := New()
	long := strings.Repeat("é", 400) + "\x1b]0;pwned\x07"
	cp, err := m.Begin(dir, 0, long)
	if err != nil {
		t.Fatalf("Begin: %v", err)
	}
	if strings.ContainsAny(cp.Label, "\n\x1b\x07") {
		t.Errorf("Label = %q, want no control characters — it reaches a terminal", cp.Label)
	}
	if n := len([]rune(cp.Label)); n > maxLabelRunes+1 {
		t.Errorf("Label is %d runes, want at most %d", n, maxLabelRunes+1)
	}
}

func TestGetRejectsPathTraversal(t *testing.T) {
	dir := newSessionDir(t)
	for _, id := range []string{"../escape", `..\escape`, "sub/dir", ""} {
		if _, err := Get(dir, id); err == nil {
			t.Errorf("Get(%q) = nil error, want a rejection", id)
		}
	}
}

func TestOutcomeStringNamesEverySkip(t *testing.T) {
	tests := []struct {
		name string
		out  Outcome
		want []string
	}{
		{"nothing happened", Outcome{}, []string{"No files"}},
		{"restored", Outcome{Restored: 1}, []string{"1 file restored"}},
		{"removed", Outcome{Deleted: 2}, []string{"2 files removed"}},
		{"mixed", Outcome{Restored: 1, Deleted: 1, SkippedSymlinks: 3},
			[]string{"1 file restored", "1 file removed", "3 symlinks skipped"}},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := tc.out.String()
			for _, want := range tc.want {
				if !strings.Contains(got, want) {
					t.Errorf("Outcome.String() = %q, want it to contain %q", got, want)
				}
			}
		})
	}
}

func TestRestoreCountsFailuresWithoutGivingUp(t *testing.T) {
	// One unwritable path must not abandon the rest: the whole point of the
	// outcome counts is that the user is told exactly what did not come back.
	if runtime.GOOS == "windows" {
		t.Skip("the read-only directory trick does not apply to Windows")
	}
	dir := newSessionDir(t)
	locked := filepath.Join(dir, "locked")
	ok := filepath.Join(dir, "ok.txt")
	write(t, locked, "locked contents")
	write(t, ok, "ok contents")

	m := New()
	_, _ = m.Begin(dir, 0, "turn")
	_ = m.Capture(dir, locked)
	_ = m.Capture(dir, ok)

	if err := os.Chmod(dir, 0o500); err != nil {
		t.Skipf("chmod unavailable: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(dir, 0o700) })

	cps, _ := m.List(dir)
	out := Restore(&cps[0])
	if out.Failed != 1 {
		t.Errorf("Failed = %d, want 1", out.Failed)
	}
	if out.Restored != 1 {
		t.Errorf("Restored = %d, want 1 — the writable file must still be restored", out.Restored)
	}
	if out.FirstErr == nil {
		t.Error("FirstErr is nil, want the underlying error for the diagnostic")
	}
}

func TestListOnASessionWithNoCheckpoints(t *testing.T) {
	// A fresh session has no checkpoint directory at all. That must read as an
	// empty history, not as an error the picker shows to the user.
	m := New()
	cps, err := m.List(filepath.Join(t.TempDir(), "never-used"))
	if err != nil {
		t.Errorf("List on a fresh session = %v, want nil", err)
	}
	if len(cps) != 0 {
		t.Errorf("got %d checkpoints, want 0", len(cps))
	}
}